### ISSUE TITLE
what's the minimum disk requirement for your fedora-kf?

### ISSUE THREAD

**Issue by Shumen** [garyedwards/fedora-kf#1]
Thank you in advance.

**Comment by garyedwards** [comment]
Hi, I have not worked on these kickstart files for a while so would not recommend using them at the moment.  I am planning to do a bit of work to them in the coming months.  At the moment I just use the fedora LXDE spin as a base and install DWM openbox etc with a custom .xinitrc

**Comment by Shumen** [comment]
I use the Fedora LXDE spin as well, but I wish to make it thiner, smaller than 512MB will be great.

**Comment by garyedwards** [comment]
Check out [Adam Miller's](https://github.com/maxamillion) [maxible](https://github.com/maxamillion/maxible) for a ansible based take on thin Fedora.
